name: stripe_example
description: Demonstrates how to use the stripe plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_stripe: ^9.1.0
  flutter_stripe:
    git:
      url: https://github.com/nguyenlamzx/flutter_stripe.git
      path: packages/stripe
      ref: b579cb08e04dcbfd8ce403341aecc55d4d3e20c1
  # flutter_stripe_web: ^4.0.0
  flutter_stripe_web:
    git:
      url: https://github.com/nguyenlamzx/flutter_stripe.git
      path: packages/stripe_web
      ref: b579cb08e04dcbfd8ce403341aecc55d4d3e20c1
  stripe_checkout: ^1.0.0
  pay: ^1.1.0
  http: ^0.13.1
  font_awesome_flutter: ^9.2.0
  platform: ^3.0.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: OtomanopeeOne
      fonts:
        - asset: fonts/OtomanopeeOne.ttf
