name: flutter_stripe_web
description: Stripe sdk bindings for the Flutter web platform. This package contains the implementation of the platform interface for web.
version: 4.3.0
homepage: https://github.com/flutter-stripe/flutter_stripe

publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.0.3
  # stripe_platform_interface: ^9.3.0
  stripe_platform_interface:
    git:
      url: https://github.com/nguyenlamzx/flutter_stripe.git
      path: packages/stripe_platform_interface
      ref: 4c89a51dee06126aedc2810f908a39318aebb953
  js: ^0.6.3
  # stripe_js: ^3.2.0
  stripe_js:
    git:
      url: https://github.com/nguyenlamzx/flutter_stripe.git
      path: packages/stripe_js
      ref: 4c89a51dee06126aedc2810f908a39318aebb953

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  freezed: ^2.3.5
  json_serializable: ^6.5.4
  lints: ^2.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebStripe
        fileName: flutter_stripe_web.dart
