name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 9.3.0
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: stripe_android
      ios:
        default_package: stripe_ios
      web:
        default_package: stripe_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  # stripe_android: ^9.3.0
  stripe_android:
    git:
      url: https://github.com/nguyenlamzx/flutter_stripe.git
      path: packages/stripe_android
      ref: 515b169eaddc43b0c564dea673b7a6f0d8f8ef02
  # stripe_ios: ^9.3.1
  stripe_ios:
    git:
      url: https://github.com/nguyenlamzx/flutter_stripe.git
      path: packages/stripe_ios
      ref: 515b169eaddc43b0c564dea673b7a6f0d8f8ef02
  # stripe_platform_interface: ^9.3.0
  stripe_platform_interface:
    git:
      url: https://github.com/nguyenlamzx/flutter_stripe.git
      path: packages/stripe_platform_interface
      ref: 515b169eaddc43b0c564dea673b7a6f0d8f8ef02

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
